services:
  - type: web
    name: dm-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: RENDER_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
